// <auto-generated />
namespace Academia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class testes011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testes011));
        
        string IMigrationMetadata.Id
        {
            get { return "201910061955253_testes011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
